environment: dev
info:
  name: Micro servicio de prueba
  version: 0.0.1
  description: Este es un micro servicio de prueba para ver que tanto se puede hacer

web:
  INSTANCE_PATH: FULL_PATH_DEL_DIRECTORIO_INSTANCE
  SERVER_NAME: '127.0.0.1:5001'
  ENV: 'development'
  SECRET_KEY: 'Set_a_very_dificult_key use mic_serv_blueprint misc generate_key'
  DEBUG: true
  BUNDLE_ERRORS: true
  PRESERVE_CONTEXT_ON_EXCEPTION: false

db:
  # connection_string: 'DATABASE CONNECTION STRING'
  hostname: hostame or ip
  db_name: database name
  db_user: database user
  db_pass: database password

logging:
  version: 1
  disable_existing_loggers: False
  formatters:
    standard:
      format: '%(asctime)s [%(levelname)s] module: %(module)s %(name)s: %(message)s'
    detailed:
      format: '%(asctime)s [%(levelname)s] module: %(module)s line: %(lineno)d %(name)s: %(message)s'
  handlers:
    wsgi:
      level: DEBUG
      stream: ext://flask.logging.wsgi_errors_stream
      formatter: standard
      class: logging.StreamHandler
    default:
      level: DEBUG
      formatter: standard
      class: logging.StreamHandler
    file_handler:
      level: DEBUG
      filename: FULL_PATH_DEL_DIRECTORIO_INSTANCE
      class: logging.handlers.RotatingFileHandler
      maxBytes: 524288000
      backupCount: 10
      formatter: standard
  root:
    level: NOTSET
    handlers: [file_handler, wsgi]
    propagate: yes
